### PR TITLE
update with initial instructions for how to boot up dev server

### LINKED ISSUE #3: README
Get the app up and running, and update the readme with instructions. Include ruby version, Postgres pre-requisite (using home-brew?) and the heroku tool belt

### PR DESCRIPTION
**Pull request by afogel**
closes #3

### CODE REVIEW

**Review by toyhammered — APPROVED** [review]
This looks great, thank you!

**Comment by afogel** [comment]
@dpaola2 can you please review? 🙏

**Comment by dpaola2** [comment]
@afogel if @toyhammered says it's good, it's good

**Comment by dpaola2** [comment]
Oh I see it's a branch rule thing. Fixing by adding @toyhammered as a maintainer.

**Review by dpaola2 — APPROVED** [review]

**Pull request merged**
